In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

# Files to Load 
income2015_to_load = "Resources/income_2015.csv"
income2014_to_load = "Resources/income_2014.csv"


# Read the Income Data
income2015_df = pd.read_csv(income2015_to_load)
income2014_df = pd.read_csv(income2014_to_load)

In [2]:
# Combine the data into a single dataset
merged_df = pd.merge(income2015_df, income2014_df, how="left", on=["GEO_ID", "GEO_ID"])

# Display the data table for preview
merged_df.head(5)

,GEO_ID,Households!!Estimate!!Total_x,"Households!!Estimate!!Less than $10,000_x","Households!!Estimate!!$10,000 to $14,999_x","Households!!Estimate!!$15,000 to $24,999_x","Households!!Estimate!!$25,000 to $34,999_x","Households!!Estimate!!$35,000 to $49,999_x","Households!!Estimate!!$50,000 to $74,999_x","Households!!Estimate!!$75,000 to $99,999_x","Households!!Estimate!!$100,000 to $149,999_x",...,"Households!!Estimate!!$25,000 to $34,999_y","Households!!Estimate!!$35,000 to $49,999_y","Households!!Estimate!!$50,000 to $74,999_y","Households!!Estimate!!$75,000 to $99,999_y","Households!!Estimate!!$100,000 to $149,999_y","Households!!Estimate!!$150,000 to $199,999_y","Households!!Estimate!!$200,000 or more_y",Households!!Estimate!!Median income (dollars)_y,Households!!Estimate!!Mean income (dollars)_y,Households!!Estimate!!PERCENT IMPUTED!!Household income in the past 12 months_y
0,1400000US08031000102,1584,5.6,2.3,8.6,8.3,6.3,24.2,11.7,19.3,...,11.2,7.6,19.9,14.4,20.1,4,8.5,70244,86999,22.8
1,1400000US08031000201,1531,7.8,7.3,9.9,6.4,21.6,15.1,14.5,12.5,...,5.6,19.9,16.7,14.7,13.7,2.5,2.5,50750,63717,26.9
2,1400000US08031000202,1676,17.1,5.6,8.8,8.2,8.1,14.3,16.3,15.1,...,6.9,9.5,13,12.8,16.8,6.7,2.7,53578,67391,25.8
3,1400000US08031000301,2660,7.6,4.5,6.8,10.8,13.2,15.7,7.3,19.2,...,8.6,14.4,18.3,7.6,20.7,7.6,4.1,57269,79421,22.6
4,1400000US08031000302,2026,0,4.6,3.7,9,16.7,13.3,12.7,20,...,9.3,12.7,13.2,16,21.3,11.4,7.1,84846,100154,18.3

In [3]:
# Export the CSV
merged_df.to_csv('income_1514.csv', index = False)