In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Load in CSV as a DataFrame
income_df = pd.read_csv('Resources/ACSST5Y2014_income_data.csv')
income_df.head(10)

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Households!!Estimate!!Total,Households!!Margin of Error!!Total,"Households!!Estimate!!Less than $10,000","Households!!Margin of Error!!Less than $10,000","Households!!Estimate!!$10,000 to $14,999","Households!!Margin of Error!!$10,000 to $14,999","Households!!Estimate!!$15,000 to $24,999","Households!!Margin of Error!!$15,000 to $24,999",...,Nonfamily households!!Estimate!!Median income ...,Nonfamily households!!Margin of Error!!Median ...,Nonfamily households!!Estimate!!Mean income (d...,Nonfamily households!!Margin of Error!!Mean in...,Nonfamily households!!Estimate!!PERCENT IMPUTE...,Nonfamily households!!Margin of Error!!PERCENT...,Nonfamily households!!Estimate!!PERCENT IMPUTE...,Nonfamily households!!Margin of Error!!PERCENT...,Nonfamily households!!Estimate!!PERCENT IMPUTE...,Nonfamily households!!Margin of Error!!PERCENT...
1,1400000US08031000102,"Census Tract 1.02, Denver County, Colorado",1534,86,4.8,2.5,2.9,2,6.5,3.2,...,44853,13335,55233,8172,(X),(X),(X),(X),15.8,(X)
2,1400000US08031000201,"Census Tract 2.01, Denver County, Colorado",1505,82,6.9,3.9,8,4.7,9.4,4.4,...,38717,13391,57615,19583,(X),(X),(X),(X),27.9,(X)
3,1400000US08031000202,"Census Tract 2.02, Denver County, Colorado",1603,90,17.2,4.2,5.5,3.1,9,4.3,...,36629,15397,60391,15914,(X),(X),(X),(X),19,(X)
4,1400000US08031000301,"Census Tract 3.01, Denver County, Colorado",2605,126,7.4,3.8,5.4,3.6,5.8,2.9,...,48321,9954,71826,18882,(X),(X),(X),(X),22.7,(X)
5,1400000US08031000302,"Census Tract 3.02, Denver County, Colorado",1959,129,0.7,1.2,4.7,4.6,3.5,2.8,...,63083,23746,75054,10548,(X),(X),(X),(X),21.6,(X)
6,1400000US08031000303,"Census Tract 3.03, Denver County, Colorado",2215,143,3.7,3.4,3.5,3.3,11.4,4.9,...,43173,14395,97869,31635,(X),(X),(X),(X),11.9,(X)
7,1400000US08031000401,"Census Tract 4.01, Denver County, Colorado",1478,62,7.5,4.4,4.4,3.2,14.8,5.2,...,44338,12675,57091,8997,(X),(X),(X),(X),29.3,(X)
8,1400000US08031000402,"Census Tract 4.02, Denver County, Colorado",2877,156,11.3,4.8,8.6,4.2,8.8,4.3,...,43639,9693,68222,11978,(X),(X),(X),(X),10.2,(X)
9,1400000US08031000501,"Census Tract 5.01, Denver County, Colorado",974,43,5.1,4.2,4.1,2.9,7.6,3.7,...,48438,9057,69850,15466,(X),(X),(X),(X),30.6,(X)

In [3]:
# Drop null values
income_df.dropna()

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Households!!Estimate!!Total,Households!!Margin of Error!!Total,"Households!!Estimate!!Less than $10,000","Households!!Margin of Error!!Less than $10,000","Households!!Estimate!!$10,000 to $14,999","Households!!Margin of Error!!$10,000 to $14,999","Households!!Estimate!!$15,000 to $24,999","Households!!Margin of Error!!$15,000 to $24,999",...,Nonfamily households!!Estimate!!Median income ...,Nonfamily households!!Margin of Error!!Median ...,Nonfamily households!!Estimate!!Mean income (d...,Nonfamily households!!Margin of Error!!Mean in...,Nonfamily households!!Estimate!!PERCENT IMPUTE...,Nonfamily households!!Margin of Error!!PERCENT...,Nonfamily households!!Estimate!!PERCENT IMPUTE...,Nonfamily households!!Margin of Error!!PERCENT...,Nonfamily households!!Estimate!!PERCENT IMPUTE...,Nonfamily households!!Margin of Error!!PERCENT...
1,1400000US08031000102,"Census Tract 1.02, Denver County, Colorado",1534,86,4.8,2.5,2.9,2,6.5,3.2,...,44853,13335,55233,8172,(X),(X),(X),(X),15.8,(X)
2,1400000US08031000201,"Census Tract 2.01, Denver County, Colorado",1505,82,6.9,3.9,8,4.7,9.4,4.4,...,38717,13391,57615,19583,(X),(X),(X),(X),27.9,(X)
3,1400000US08031000202,"Census Tract 2.02, Denver County, Colorado",1603,90,17.2,4.2,5.5,3.1,9,4.3,...,36629,15397,60391,15914,(X),(X),(X),(X),19,(X)
4,1400000US08031000301,"Census Tract 3.01, Denver County, Colorado",2605,126,7.4,3.8,5.4,3.6,5.8,2.9,...,48321,9954,71826,18882,(X),(X),(X),(X),22.7,(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,1400000US08031015500,"Census Tract 155, Denver County, Colorado",1744,73,8.9,3.6,9.2,4.5,11.8,4.7,...,33170,3090,37829,4823,(X),(X),(X),(X),30.4,(X)
141,1400000US08031015600,"Census Tract 156, Denver County, Colorado",2124,118,17.1,6.3,11.9,4.7,18.3,7.1,...,16250,3779,29793,8142,(X),(X),(X),(X),29.5,(X)
142,1400000US08031015700,"Census Tract 157, Denver County, Colorado",2064,118,11.9,5.1,6.1,5.4,8.3,4.3,...,25873,6281,32231,6375,(X),(X),(X),(X),26.4,(X)
143,1400000US08031980000,"Census Tract 9800, Denver County, Colorado",503,78,4.4,3.8,12.1,7.4,9.1,7.1,...,44196,8617,44820,10190,(X),(X),(X),(X),6.3,(X)
144,1400000US08031980100,"Census Tract 9801, Denver County, Colorado",0,12,-,**,-,**,-,**,...,-,**,-,**,(X),(X),(X),(X),-,(X)

In [4]:
# Keep columns: income less than 50K
income_df50  = income_df.filter(['GEO_ID','S1901_C01_001E','S1901_C01_002E','S1901_C01_003E','S1901_C01_004E','S1901_C01_005E','S1901_C01_006E'])
income_df50

,GEO_ID,S1901_C01_001E,S1901_C01_002E,S1901_C01_003E,S1901_C01_004E,S1901_C01_005E,S1901_C01_006E
0,id,Households!!Estimate!!Total,"Households!!Estimate!!Less than $10,000","Households!!Estimate!!$10,000 to $14,999","Households!!Estimate!!$15,000 to $24,999","Households!!Estimate!!$25,000 to $34,999","Households!!Estimate!!$35,000 to $49,999"
1,1400000US08031000102,1534,4.8,2.9,6.5,11.2,7.6
2,1400000US08031000201,1505,6.9,8,9.4,5.6,19.9
3,1400000US08031000202,1603,17.2,5.5,9,6.9,9.5
4,1400000US08031000301,2605,7.4,5.4,5.8,8.6,14.4
...,...,...,...,...,...,...,...
140,1400000US08031015500,1744,8.9,9.2,11.8,21,18.1
141,1400000US08031015600,2124,17.1,11.9,18.3,14.4,14.3
142,1400000US08031015700,2064,11.9,6.1,8.3,15.6,18.2
143,1400000US08031980000,503,4.4,12.1,9.1,6,25.4
144,1400000US08031980100,0,-,-,-,-,-

In [5]:
# Keep columns: income greater than 50K, less than 150K
income_df150  = income_df.filter(['GEO_ID','S1901_C01_001E','S1901_C01_007E','S1901_C01_008E','S1901_C01_009E'])
income_df150

,GEO_ID,S1901_C01_001E,S1901_C01_007E,S1901_C01_008E,S1901_C01_009E
0,id,Households!!Estimate!!Total,"Households!!Estimate!!$50,000 to $74,999","Households!!Estimate!!$75,000 to $99,999","Households!!Estimate!!$100,000 to $149,999"
1,1400000US08031000102,1534,19.9,14.4,20.1
2,1400000US08031000201,1505,16.7,14.7,13.7
3,1400000US08031000202,1603,13,12.8,16.8
4,1400000US08031000301,2605,18.3,7.6,20.7
...,...,...,...,...,...
140,1400000US08031015500,1744,17.6,6.3,6.1
141,1400000US08031015600,2124,14.6,4.5,1.8
142,1400000US08031015700,2064,12.9,12.1,9.4
143,1400000US08031980000,503,25.6,7,5.2
144,1400000US08031980100,0,-,-,-

In [6]:
# Keep columns: income greater than 150K
income_df_greaterthan150  = income_df.filter(['GEO_ID','S1901_C01_001E','S1901_C01_010E','S1901_C01_011E'])
income_df_greaterthan150

,GEO_ID,S1901_C01_001E,S1901_C01_010E,S1901_C01_011E
0,id,Households!!Estimate!!Total,"Households!!Estimate!!$150,000 to $199,999","Households!!Estimate!!$200,000 or more"
1,1400000US08031000102,1534,4,8.5
2,1400000US08031000201,1505,2.5,2.5
3,1400000US08031000202,1603,6.7,2.7
4,1400000US08031000301,2605,7.6,4.1
...,...,...,...,...
140,1400000US08031015500,1744,0.8,0
141,1400000US08031015600,2124,1.9,1.3
142,1400000US08031015700,2064,3.4,2.1
143,1400000US08031980000,503,0,5.2
144,1400000US08031980100,0,-,-

In [7]:
# Keep columns: Household Median and Mean income and percent allocated
income_df_MedMean  = income_df.filter(['GEO_ID','S1901_C01_001E','S1901_C01_012E','S1901_C01_013E','S1901_C01_014E'])
income_df_MedMean

,GEO_ID,S1901_C01_001E,S1901_C01_012E,S1901_C01_013E,S1901_C01_014E
0,id,Households!!Estimate!!Total,Households!!Estimate!!Median income (dollars),Households!!Estimate!!Mean income (dollars),Households!!Estimate!!PERCENT IMPUTED!!Househo...
1,1400000US08031000102,1534,70244,86999,22.8
2,1400000US08031000201,1505,50750,63717,26.9
3,1400000US08031000202,1603,53578,67391,25.8
4,1400000US08031000301,2605,57269,79421,22.6
...,...,...,...,...,...
140,1400000US08031015500,1744,34559,42688,27.9
141,1400000US08031015600,2124,26480,39131,24.2
142,1400000US08031015700,2064,41432,55379,25.8
143,1400000US08031980000,503,47936,55675,21.7
144,1400000US08031980100,0,-,-,-

In [8]:
#Drop Margin of Error columns that are pulling into csv
MOE_df = income_df.loc[:,income_df.columns.str.contains('M$')]
MOE_df
data = data.drop(columns="area")

,S1901_C01_001M,S1901_C01_002M,S1901_C01_003M,S1901_C01_004M,S1901_C01_005M,S1901_C01_006M,S1901_C01_007M,S1901_C01_008M,S1901_C01_009M,S1901_C01_010M,...,S1901_C04_007M,S1901_C04_008M,S1901_C04_009M,S1901_C04_010M,S1901_C04_011M,S1901_C04_012M,S1901_C04_013M,S1901_C04_014M,S1901_C04_015M,S1901_C04_016M
0,Households!!Margin of Error!!Total,"Households!!Margin of Error!!Less than $10,000","Households!!Margin of Error!!$10,000 to $14,999","Households!!Margin of Error!!$15,000 to $24,999","Households!!Margin of Error!!$25,000 to $34,999","Households!!Margin of Error!!$35,000 to $49,999","Households!!Margin of Error!!$50,000 to $74,999","Households!!Margin of Error!!$75,000 to $99,999","Households!!Margin of Error!!$100,000 to $149,999","Households!!Margin of Error!!$150,000 to $199,999",...,"Nonfamily households!!Margin of Error!!$50,000...","Nonfamily households!!Margin of Error!!$75,000...","Nonfamily households!!Margin of Error!!$100,00...","Nonfamily households!!Margin of Error!!$150,00...","Nonfamily households!!Margin of Error!!$200,00...",Nonfamily households!!Margin of Error!!Median ...,Nonfamily households!!Margin of Error!!Mean in...,Nonfamily households!!Margin of Error!!PERCENT...,Nonfamily households!!Margin of Error!!PERCENT...,Nonfamily households!!Margin of Error!!PERCENT...
1,86,2.5,2,3.2,4.8,3.7,6.9,4.3,5.4,2.4,...,10.2,4.4,5.8,2.7,2.5,13335,8172,(X),(X),(X)
2,82,3.9,4.7,4.4,3.1,5.7,5.5,4.7,5,2.1,...,7.3,6,5.9,1.9,7.5,13391,19583,(X),(X),(X)
3,90,4.2,3.1,4.3,3.7,4.3,4.3,4.3,5.4,3.9,...,6.5,7,8.7,3.1,2.9,15397,15914,(X),(X),(X)
4,126,3.8,3.6,2.9,4.3,4.9,5.3,3.5,5.4,3.9,...,7.2,5.1,6.9,3.3,4.9,9954,18882,(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,73,3.6,4.5,4.7,6.6,5.4,5.7,3.3,3.4,1.3,...,6.9,3.4,4.2,2.8,2.8,3090,4823,(X),(X),(X)
141,118,6.3,4.7,7.1,6.3,5.1,5.6,3.3,1.9,2.3,...,5.2,3.7,4.6,5.4,4,3779,8142,(X),(X),(X)
142,118,5.1,5.4,4.3,6.9,6.6,5.6,6.8,5,3.6,...,9.8,4,4.5,4,4,6281,6375,(X),(X),(X)
143,78,3.8,7.4,7.1,4.2,11.4,9.7,5.7,5,6.3,...,8.7,5.1,11.4,14.5,14.5,8617,10190,(X),(X),(X)
144,12,**,**,**,**,**,**,**,**,**,...,**,**,**,**,**,**,**,(X),(X),(X)

In [10]:
# Export the CSV
income_df.to_csv('income_2014.csv', index = False)