In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Load in CSV as a DataFrame
income_df = pd.read_csv('Resources/ACSST5Y2018_income_data.csv')
income_df.head(10)

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households MOE!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households MOE!!Total!!Less t...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households MOE!!Total!!$10,00...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households MOE!!Total!!$15,00...",...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households MOE!!Med...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households MOE!!Mea...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households MOE!!PER...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households MOE!!PER...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households MOE!!PER...
1,1400000US08031000102,"Census Tract 1.02, Denver County, Colorado",1613,79,5.6,3.7,2.7,1.9,8.4,4.0,...,60368,13516,86644,17978,(X),(X),(X),(X),31.6,(X)
2,1400000US08031000201,"Census Tract 2.01, Denver County, Colorado",1618,86,4.6,3.2,9.4,5.0,10.4,4.8,...,39167,12212,51177,8355,(X),(X),(X),(X),33.9,(X)
3,1400000US08031000202,"Census Tract 2.02, Denver County, Colorado",1737,79,17.9,6.0,4.7,3.9,5.1,3.7,...,32695,9026,61242,14203,(X),(X),(X),(X),27.1,(X)
4,1400000US08031000301,"Census Tract 3.01, Denver County, Colorado",2856,106,9.3,4.4,2.1,1.9,5.2,4.6,...,47500,15890,67413,13719,(X),(X),(X),(X),36.7,(X)
5,1400000US08031000302,"Census Tract 3.02, Denver County, Colorado",2131,89,0.9,1.4,1.7,2.0,2.8,2.6,...,74932,12184,131447,47643,(X),(X),(X),(X),28.0,(X)
6,1400000US08031000303,"Census Tract 3.03, Denver County, Colorado",2160,191,3.4,3.5,2.7,2.3,5.3,2.9,...,68065,18907,101258,21277,(X),(X),(X),(X),25.1,(X)
7,1400000US08031000401,"Census Tract 4.01, Denver County, Colorado",1464,75,7.5,4.9,6.1,4.1,6.6,4.3,...,56818,31038,71625,11307,(X),(X),(X),(X),33.0,(X)
8,1400000US08031000402,"Census Tract 4.02, Denver County, Colorado",2984,209,4.0,2.9,4.0,3.3,9.5,4.7,...,79659,10303,98214,14417,(X),(X),(X),(X),28.8,(X)
9,1400000US08031000501,"Census Tract 5.01, Denver County, Colorado",959,61,3.2,3.7,0.6,1.0,5.2,3.0,...,74464,30530,93625,19674,(X),(X),(X),(X),28.1,(X)

In [3]:
# Drop null values
income_df.dropna()

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households MOE!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households MOE!!Total!!Less t...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households MOE!!Total!!$10,00...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households MOE!!Total!!$15,00...",...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households MOE!!Med...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households MOE!!Mea...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households MOE!!PER...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households MOE!!PER...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households MOE!!PER...
1,1400000US08031000102,"Census Tract 1.02, Denver County, Colorado",1613,79,5.6,3.7,2.7,1.9,8.4,4.0,...,60368,13516,86644,17978,(X),(X),(X),(X),31.6,(X)
2,1400000US08031000201,"Census Tract 2.01, Denver County, Colorado",1618,86,4.6,3.2,9.4,5.0,10.4,4.8,...,39167,12212,51177,8355,(X),(X),(X),(X),33.9,(X)
3,1400000US08031000202,"Census Tract 2.02, Denver County, Colorado",1737,79,17.9,6.0,4.7,3.9,5.1,3.7,...,32695,9026,61242,14203,(X),(X),(X),(X),27.1,(X)
4,1400000US08031000301,"Census Tract 3.01, Denver County, Colorado",2856,106,9.3,4.4,2.1,1.9,5.2,4.6,...,47500,15890,67413,13719,(X),(X),(X),(X),36.7,(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,1400000US08031015500,"Census Tract 155, Denver County, Colorado",1843,84,5.0,3.4,2.2,1.9,7.2,4.0,...,44189,7829,57082,6576,(X),(X),(X),(X),28.0,(X)
141,1400000US08031015600,"Census Tract 156, Denver County, Colorado",2407,120,17.9,6.7,5.0,3.3,7.8,5.6,...,26444,24648,42438,16864,(X),(X),(X),(X),30.1,(X)
142,1400000US08031015700,"Census Tract 157, Denver County, Colorado",2187,120,12.3,5.3,7.5,5.3,9.1,5.8,...,38030,19530,43071,11575,(X),(X),(X),(X),17.4,(X)
143,1400000US08031980000,"Census Tract 9800, Denver County, Colorado",636,41,0.0,5.0,7.1,6.1,9.4,6.5,...,41818,5094,47054,7155,(X),(X),(X),(X),31.6,(X)
144,1400000US08031980100,"Census Tract 9801, Denver County, Colorado",0,12,-,**,-,**,-,**,...,-,**,-,**,(X),(X),(X),(X),-,(X)

In [8]:
# Keep columns: income less than 50K
income_df50  = income_df.filter(['GEO_ID','S1901_C01_001E','S1901_C01_002E','S1901_C01_003E','S1901_C01_004E','S1901_C01_005E','S1901_C01_006E'])
income_df50

,GEO_ID,S1901_C01_001E,S1901_C01_002E,S1901_C01_003E,S1901_C01_004E,S1901_C01_005E,S1901_C01_006E
0,id,Estimate!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Estimate!!Households!!Total!!$10,000 to $14,999","Estimate!!Households!!Total!!$15,000 to $24,999","Estimate!!Households!!Total!!$25,000 to $34,999","Estimate!!Households!!Total!!$35,000 to $49,999"
1,1400000US08031000102,1613,5.6,2.7,8.4,10.6,4.6
2,1400000US08031000201,1618,4.6,9.4,10.4,6.7,15.9
3,1400000US08031000202,1737,17.9,4.7,5.1,11.7,6.8
4,1400000US08031000301,2856,9.3,2.1,5.2,7.0,12.3
...,...,...,...,...,...,...,...
140,1400000US08031015500,1843,5.0,2.2,7.2,18.3,15.1
141,1400000US08031015600,2407,17.9,5.0,7.8,10.1,16.4
142,1400000US08031015700,2187,12.3,7.5,9.1,9.8,16.6
143,1400000US08031980000,636,0.0,7.1,9.4,6.9,18.4
144,1400000US08031980100,0,-,-,-,-,-

In [9]:
# Keep columns: income greater than 50K, less than 150K
income_df150  = income_df.filter(['GEO_ID','Estimate Occupied housing units','S1901_C01_007E','S1901_C01_008E','S1901_C01_009E'])
income_df150

,GEO_ID,S1901_C01_007E,S1901_C01_008E,S1901_C01_009E
0,id,"Estimate!!Households!!Total!!$50,000 to $74,999","Estimate!!Households!!Total!!$75,000 to $99,999","Estimate!!Households!!Total!!$100,000 to $149,999"
1,1400000US08031000102,11.7,10.0,18.5
2,1400000US08031000201,18.0,12.4,16.3
3,1400000US08031000202,15.5,13.2,17.2
4,1400000US08031000301,15.0,10.8,14.6
...,...,...,...,...
140,1400000US08031015500,21.8,18.2,8.6
141,1400000US08031015600,19.1,7.6,10.5
142,1400000US08031015700,18.2,4.9,12.8
143,1400000US08031980000,29.6,15.3,11.9
144,1400000US08031980100,-,-,-

In [10]:
# Keep columns: income greater than 150K
income_df_greaterthan150  = income_df.filter(['GEO_ID','Estimate Occupied housing units','S1901_C01_010E','S1901_C01_011E'])
income_df_greaterthan150

,GEO_ID,S1901_C01_010E,S1901_C01_011E
0,id,"Estimate!!Households!!Total!!$150,000 to $199,999","Estimate!!Households!!Total!!$200,000 or more"
1,1400000US08031000102,12.7,15.1
2,1400000US08031000201,2.5,3.6
3,1400000US08031000202,3.5,4.4
4,1400000US08031000301,13.9,9.8
...,...,...,...
140,1400000US08031015500,2.2,1.3
141,1400000US08031015600,2.5,3.1
142,1400000US08031015700,7.2,1.6
143,1400000US08031980000,0.0,1.4
144,1400000US08031980100,-,-

In [11]:
# Keep columns: Household Median and Mean income and percent allocated
income_df_MedMean  = income_df.filter(['GEO_ID','Estimate Occupied housing units','S1901_C01_012E','S1901_C01_013E','S1901_C01_014E'])
income_df_MedMean

,GEO_ID,S1901_C01_012E,S1901_C01_013E,S1901_C01_014E
0,id,Estimate!!Households!!Median income (dollars),Estimate!!Households!!Mean income (dollars),Estimate!!Households!!PERCENT ALLOCATED!!House...
1,1400000US08031000102,87798,110975,38.7
2,1400000US08031000201,55541,71556,34.6
3,1400000US08031000202,57181,71824,28.2
4,1400000US08031000301,72173,98274,34.4
...,...,...,...,...
140,1400000US08031015500,52057,62033,28.3
141,1400000US08031015600,44816,60435,35.5
142,1400000US08031015700,46959,61974,31.0
143,1400000US08031980000,54592,59537,25.6
144,1400000US08031980100,-,-,-

In [12]:
# Export the CSV
income_df.to_csv('income_2018.csv', index = False)