In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

# Files to Load 
income1514_to_load = "Resources/income_1514.csv"
income_1_to_load = "Resources/income_1.csv"


# Read the Income Data
income1514_df = pd.read_csv(income1514_to_load)
income_1_df = pd.read_csv(income_1_to_load)

In [3]:
# Combine the data into a single dataset
merged_df = pd.merge(income1514_df, income_1_df, how="left", on=["GEO_ID", "GEO_ID"])

# Display the data table for preview
merged_df.head(5)

,GEO_ID,Households!!Estimate!!Total_x,"Households!!Estimate!!Less than $10,000_x","Households!!Estimate!!$10,000 to $14,999_x","Households!!Estimate!!$15,000 to $24,999_x","Households!!Estimate!!$25,000 to $34,999_x","Households!!Estimate!!$35,000 to $49,999_x","Households!!Estimate!!$50,000 to $74,999_x","Households!!Estimate!!$75,000 to $99,999_x","Households!!Estimate!!$100,000 to $149,999_x",...,"Households!!Estimate!!$15,000 to $24,999","Households!!Estimate!!$25,000 to $34,999","Households!!Estimate!!$35,000 to $49,999","Households!!Estimate!!$50,000 to $74,999","Households!!Estimate!!$75,000 to $99,999","Households!!Estimate!!$100,000 to $149,999","Households!!Estimate!!$150,000 to $199,999","Households!!Estimate!!$200,000 or more",Households!!Estimate!!Median income (dollars),Households!!Estimate!!Mean income (dollars)
0,1400000US08031000102,1584,5.6,2.3,8.6,8.3,6.3,24.2,11.7,19.3,...,6.7,8.3,6.1,16.8,11.1,23.5,9.1,10.7,82917,101053
1,1400000US08031000201,1531,7.8,7.3,9.9,6.4,21.6,15.1,14.5,12.5,...,8.1,7.1,18.9,18.6,12.2,14.5,1.8,2.4,49342,68494
2,1400000US08031000202,1676,17.1,5.6,8.8,8.2,8.1,14.3,16.3,15.1,...,8.9,9.1,7.1,17.6,14.9,13.5,3.2,3.8,52453,68191
3,1400000US08031000301,2660,7.6,4.5,6.8,10.8,13.2,15.7,7.3,19.2,...,6.5,10.4,10.3,19.6,9.2,18.1,8.6,8,61658,88226
4,1400000US08031000302,2026,0,4.6,3.7,9,16.7,13.3,12.7,20,...,4.4,7.4,16.7,14.8,12.6,17.9,11.9,9.8,79405,113807

In [5]:
# Export the CSV
merged_df.to_csv('income_final.csv', index = False)